version: '3.7'

services:
  web:
    build: .
    environment:
      - LETSENCRYPT_HOST=mail.reyah.dev
      - VIRTUAL_HOST=mail.reyah.dev
      - DATABASE_URL=mysql://root:the.0nly.Queen@mysql:3306/mail
      - HOST=mail.reyah.dev
      - PORT=80
    volumes:
      - ../docker-data:/app/docker-data
    networks:
      - mysql
      - proxy

networks:
  mysql:
    name: mysql
  proxy:
    name: proxy
