version: '3.7'

services:
  mysql_db:
    container_name: balaAdminDB
    image: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpPass
      MYSQL_ROOT_PASSWORD: adminpPass
      MYSQL_DATABASE: admin
    ports:
      - "3308:3306"
    volumes:
      - mysql_db_bala:/var/lib/mysql
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: www.baladiya.com
    # example.com should be replaced with the own domain for the mail server:
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      # Path should be adjusted accordingly:
      - ./docker-data/nginx-proxy/certs/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      # If letsencrypt for SSL/TLS certificate is used (otherwise adapt)
      # - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE      
volumes:
  mysql_db_bala:
  docker-data:

